//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubDesktop
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;

    public partial class Training
    {
        public System.DateTime date { get; set; }
        public short fkey_member { get; set; }
        public short fkey_trainer { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Trainer Trainer { get; set; }

        public override string ToString()
        {
            using (var db = new SportClubEntities())
            {
                return $"Date: {date}\nMember: {db.Members.First(x=>x.id_gkey == fkey_member).fio}\nTrainer: {db.Trainers.First(x => x.id_gkey == fkey_trainer).fio}\nCost: {((decimal)cost).ToString("C", CultureInfo.CurrentCulture)}\n";

            }
        }
    }
}
