//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportClubDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public System.DateTime date { get; set; }
        public short fkey_member { get; set; }
        public short fkey_trainer { get; set; }
        public Nullable<decimal> cost { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
